name: Docs to PDF
on:
  push:
    branches:
      - main
    paths:
      - "**.md"

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: /github/workspace/
          output_dir: /github/workspace/pdfs
          images_dir: /github/workspace/images
          image_import: /github/workspace/images
          build_html: false
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: /github/workspace/pdfs
